### ISSUE TITLE
Update applies 'null' string to null column values

### ISSUE THREAD

**Issue by jacargentina** [orbitaloop/WebSqlSync#30]
I've detected a bug which saves the 'null' string to null values coming from the service,

The bug is on the _buildUpdateSQL function, which generates the update string by doing "FIELD" = "VALUE", where it should be "FIELD" = VALUE

**Comment by orbitaloop** [comment]
Thanks.
I don't have time to test your fix, but I added a comment, so next people having this problem and testing the change can make a pull request
