### ISSUE TITLE
How to manage ids ?

### ISSUE THREAD

**Issue by chOse** [orbitaloop/WebSqlSync#41]
Hello orbitaloop,

thank you for this awesome library. I'm trying to get it to work on my project.

I'm not sure how to manage ids for client and server db structure.

Could you give a quick example for a small table structure (eg: Contacts : id, name) on both side :
- what id fields are required ?
- which one is the primary key on its own side
- which one is the id that refers to the other side's primary key ?
- which one needs to be sent by the client to the server ?
- which one does the server needs to specify in its reply ?

That would make the installation a lot easier for me

Thanks very much

**Comment by orbitaloop** [comment]
Thanks @abeauseigle . FYI, the current code is also working on a 2 way sides and multi browser/multi-devices (iOS, Android, Chrome/Safari). With more than 50 000 sync everyday.
And we are planning to update the library to be even more robust against network failure and bugs
