### ISSUE TITLE
Fails if column in table has same name as table 

### ISSUE THREAD

**Issue by tomchiverton** [orbitaloop/WebSqlSync#45]
e.g. with
CREATE TABLE IF NOT EXISTS feedback (id integer primary key, date datetime, name varchar, email varchar, feedback varchar )
the query constructed by _getDataToSave is
SELECT * FROM feedback WHERE id in IN (SELECT DISTINCT id FROM new_elem WHERE table_name="feedback")'
which returns no results despite entries in new_elem table. 
Even in the Chrome developer console, no results.
If you replace the inner query with a static list of number in the dev console, all is OK.
If you try the original query but with ' instead of " in the dev console, all is as expected, but I just renamed the table rather than try with altering the code.

**Comment by luigi37** [comment]
Maybe not related but... is "WHERE id in IN"  a typo on the request or the actual code?

**Comment by tomchiverton** [comment]
"in IN" is a typo here, not the code :-)

**Comment by orbitaloop** [comment]
Strange. We are planning to update the library to be even more robust against network failure and bugs
