### ISSUE TITLE
Problem with Cordova/Phonegap and WP8

### ISSUE THREAD

**Issue by luigi37** [orbitaloop/WebSqlSync#46]
Hi,
I'm using succesfully this script (abeausiegle version) to sync client and server on cordova app for Android and iOS.
On WP8 (Phonegap Build) I'm facing issues because the call to the server does not work properly.
After some investigation I found that the "offending" part is:

    XHR.upload.addEventListener("progress", uploadProgressCallBack, false);	// See matlus.com/html5-file-upload-with-progress/
    XHR.addEventListener("progress", downloadProgressCallBack, false);	

It seems that this produce a javascript error which unfortunately I cannot capture with my development environment.

Anyway, commenting out those lines, everything seems to work...

Can I just comment out those lines? Any negative effect?

Thanks a lot!

**Comment by orbitaloop** [comment]
No negative effect, except the lack of progress feedback
