### ISSUE TITLE
persistence.js

### ISSUE THREAD

**Issue by siddo420** [orbitaloop/WebSqlSync#48]
This is not exactly an issue but if persistencejs can work with sqlite then whats the purpose of this project ie. how is it different from persistencejs?

Sorry, I am new to this and working on an app using node.js on server side.

**Comment by siddo420** [comment]
Has WebSQLSync been tested with SQLite (Cordova plugin)?

**Comment by jeroendeswaef** [comment]
As far as I know, It only has been tested with the SQLite DB's from the WebView on iOS/Android and on Chrome. Not with the SQLite Cordova plugin

**Comment by jeroendeswaef** [comment]
persistence.js abstracts away the underlying database technology and gives a common api. While you can share data models between client and server, it doesn't sync the data. 
If you also want to be able to synchronize with persistence.js, you also have to make use of [persistence.sync.js](https://github.com/coresmart/persistencejs/blob/master/docs/sync.md)

The core purpose of this library instead, is to be able to sync data between client and server, while working with SQL on the client.
