### ISSUE TITLE
Not all modified items sent to the server

### ISSUE THREAD

**Issue by joydasolive** [orbitaloop/WebSqlSync#49]
I have been using this library for some time and most of the time it works a treat. Thank you for the lib. However, sometimes it doesn't send all the modified data to the server. Any idea what could be causing this issue. I have been trying to figure out but not sure if I am looking at the right direction.

So, I have tables in the client side that stores  sale, sales items and payments. Every time a sale gets completed, these tables are updated and they get sent to the server and the server processes it and send back to update few columns in the client side. I have a db transaction that updates the sales, sales items and payments to "Completed" and in the callback calls the sync function. There are about 20 clients that have been using it and about 99% of the time it works as expected. the But sometimes, the sales items are not sent to the server once a sale completes. The payment info gets sent before the actual sale info(this gets sent on next sync). What might be causing this issue? I was saving the whole JSON to examine it and see no traces of the completed sales items going to server. I couldn't replicate the issue from my end but looking at the client data I could see few of them having it and only once or twice a day.

Anyone could shed a light on this please?

**Comment by jeroendeswaef** [comment]
Hi,

For the sync, it uses a trigger on UPDATE/INSERT and it writes the id's to sync in a table called `new_elem`.
After the sync finishes, it clears all id's sent with the sync from the table `new_elem`.
The purpose of this is to sync only the data that have changed.

One thing that could be causing issues, is if you start a second sync, before the previous sync has finished.

**Comment by joydasolive** [comment]
Hi Jeroen,

As I call sync twice(now realised that one can be omitted) successively on page load which sometimes have some "GET" data to populate  DB with, lets see if removing one solves the issue. I am not sure why it happens only in 1 in 100ish cases.

Anyway, Grazie Mille! :)

**Comment by orbitaloop** [comment]
Strange, it should not. We are planning to update the plugin to be even more robust against network failure and bugs
