### ISSUE TITLE
Undefined value in last_sync field 

### ISSUE THREAD

**Issue by shahid3602** [orbitaloop/WebSqlSync#51]
i used this code to synchronize data between websql and mysql but last_sync field of table sync_info holds undefined value.

**Comment by Kaddath-R** [comment]
Hello,
I had the same problem, actually it comes from the php handler, SqlSyncHandler.php, in lines 14 in 51 (or around there), just replace sync_date with syncDate. It was bad formatted.

**Comment by orbitaloop** [comment]
Thanks Kaddath-R, I just changed the name of the variable
