### ISSUE TITLE
Synchroning mobile( An ionic/cordova app) sqlite database with server and server to mobile database

### ISSUE THREAD

**Issue by gobimca2012** [orbitaloop/WebSqlSync#54]
I am new to ionic/Cordova framework. I am using sqlite to store the data (url : https://github.com/litehelpers/Cordova-sqlite-storage). I can successfully store data in local. But now mobile user want to synchronize their data with server ( **SQL server 2012**). Because they are using mobile app and also web application. when user login in mobile, i am getting initial data as json result from server (Via ASP.NET Rest API)and then storing data in sqlite db. 

I search on web, finally i found WebSqlSync. But i dont know how to sync with server and server to movile database.

Please help me to achieve this. 

**Gobinath R**,
gobimca2012@gmail.com

You can contact me at any time...

**Comment by ankarthik** [comment]
@gobimca2012 

Did you get any solution for this?

Thanks.

**Comment by kuzun9x** [comment]
@gobimca2012 @ankarthik 
How about your solution?
I try to look for solution: sqlite-sync, realm,...
But it seems not suitable for me. sqlite-sync just support java server, realm maybe not support ionic

**Comment by orbitaloop** [comment]
Hi,
It's possible, but you will have to code the ASP.NET server part. If you know how to read a JSON and insert data in SQL Server, it should not be too complicated. You can use some example of server-side code in the repository.
I'm sorry to not be able to do more, but I'm very busy with too many projects

**Comment by mota57** [comment]
hey any news?
