### ISSUE TITLE
Web Sql is no longer in active maintenance.

### ISSUE THREAD

**Issue by niravjgandhi** [orbitaloop/WebSqlSync#56]
**If web sql database are no longer available then how this JS work for the future.**
Actually I want to create a new NodeJS App in which I need to use this js. But when I read this article, I really bit confuse for use this JS or NOT. Please help me.
Here is the official link from the W3C
[https://www.w3.org/TR/webdatabase/](url)
W3C suggesting to use indexedDb rather than WEB SQL DATABASE. 
So any js that you made to sync indexeddb database to MYSQL And MYSQL To IndexedDB.

And if any body have knowledge of how to sync document type database to MYSQL Database. Please help me.

**Comment by orbitaloop** [comment]
Yes, I know, but I don't see it removed anytime soon. Even Google and Apple are using Web SQL in some of their web apps. And for mobile apps, there are Cordova plugins to have SQL Lite, so it will be always working.
And this code is running well in hundreds of apps, some of them have millions of download.
