### ISSUE TITLE
How to add a loader/counter

### ISSUE THREAD

**Issue by abhilashrajrs** [orbitaloop/WebSqlSync#60]
Hi, I want to show the counter for Insert, but don't know how to add it. Here the screenshot on what I am working for. http://take.ms/OWOX4

Please help me on this...

**Comment by luigi37** [comment]
Hi 
Problem is likely that, being sql command asyncronous, you print the output before getting the final result (the query goes in parallel execution with the rest of your code).
I think you should insert the counter inside the sql command as a callback...

**Comment by abhilashrajrs** [comment]
Can able to provide a sample code

**Comment by luigi37** [comment]
Hi can you post a portion of your code?

**Comment by abhilashrajrs** [comment]
applyQusChanges: function(quss, lastserverSync, lastSync, callback) {
        this.db.transaction(
            function(tx) {
                var l = quss.length;
				var successCountQus = 0;
                var sql = "INSERT OR REPLACE INTO question (qus_id, qus, qus_ans1, qus_ans2, qus_ans3, qus_ans4, qus_cans, qus_description, qus_cat, qus_exam, qus_activate) " + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
                log('Inserting or Updating in local database:');				
                var e;
                for (var i = 0; i < l; i++) {
                    e = quss[i];
                    //log(e.qus_id + ' ' + e.qus + ' ' + e.qus_ans1 + ' ' + e.qus_ans2 + ' ' + e.qus_ans3 + ' ' + e.qus_ans4 + ' ' + e.qus_cans + ' ' + e.qus_description + ' ' + e.qus_cat + ' ' + e.qus_exam + ' ' + e.qus_activate);
                    var params = [e.qus_id, e.qus, e.qus_ans1, e.qus_ans2, e.qus_ans3, e.qus_ans4, e.qus_cans, e.qus_description, e.qus_cat, e.qus_exam, e.qus_activate];
                    tx.executeSql(sql, params);					
**here the for loop ends**

				}
				
                log('Synchronization complete (' + l + ' items synchronized)');
				$('#task4').toggleClass('tasklist-completed');
				$('#task5').show();
            },
            this.txErrorHandler,
            function(tx) {
                callback();
            }
        );
    },

**Comment by abhilashrajrs** [comment]
Yes, i added the portion of code

**Comment by luigi37** [comment]
I assume your problem is that instead of a counting counter, you visualize just a certain value...

You should put the code which increment and show the counter, inside the callback called on success of executesql  like:

 tx.executeSql(mySQL, myVar,function(){console.log('All good, here my counter);},function(){console.log('error in executeSQL');});

Hope this help

**Comment by abhilashrajrs** [comment]
not working, it shows the total count instantly

**Comment by abhilashrajrs** [comment]
it's working now, thank you very much

**Comment by luigi37** [comment]
Cool. I guess can be closed now :-)

**Comment by abhilashrajrs** [comment]
Yes
