### ISSUE TITLE
WebSQL Deprecation

### ISSUE THREAD

**Issue by ccsmith13** [orbitaloop/WebSqlSync#63]
Web SQL is on its way out and is being slowly <a href=”https://developer.chrome.com/blog/deprecating-web-sql/#web-sql-deprecation-and-removal-steps”>deprecated</a>. Web SQL access in insecure contexts is deprecated as of Chromium 105 and a warning message is shown in the Chrome DevTools Issue panel. It's planned to fully remove it in later versions. Unfortunately, it seems like this repository may need to be archived as a result of WebSQL deprecation.

**Comment by pwFoo** [comment]
Searching for a DB two way data sync solution between browser / clients and a remote server as base for a (small) project...
Any successor for WebSqlSync?

**Comment by orbitaloop** [comment]
This code is still used in many apps, and will always work. IndeedWebSQL uses SQL Lite behind the scene, so for mobile apps, there are many plugins to use SQLite, and for browsers, there is SQLite JS.
So no need to archive ;-)
